2018-12-09 14:36:28,640 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().pagginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
2018-12-09 14:36:35,831 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().pagginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
2018-12-09 14:36:37,019 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().pagginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
2018-12-09 14:37:11,625 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().paginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
2018-12-09 14:37:12,443 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().paginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
2018-12-09 14:37:21,970 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 14:43:37,495 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
