2018-12-09 12:20:28,786 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:42]
2018-12-09 12:22:15,628 ERROR: Exception on /edit_profile [POST] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 93, in edit_profile
    db.session.commit()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 774, in _emit_update_statements
    execute(statement, multiparams)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('buttusova', 'Some added info ', 1)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-12-09 12:31:36,011 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 12:52:40,982 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 12:52:53,397 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 12:53:17,766 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 12:54:17,500 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 13:01:08,466 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 13:18:26,973 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 13:25:34,277 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 14:15:40,175 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 14:23:02,005 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 14:34:21,456 INFO: Microblog startup [in /mnt/d/diploma/flask_mega_tutorial/microblog/app/__init__.py:43]
2018-12-09 14:34:35,051 ERROR: Exception on /index [GET] [in /mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/d/diploma/flask_mega_tutorial/microblog/app/routes.py", line 29, in index
    posts = current_user.followed_posts().pagginate(
AttributeError: 'BaseQuery' object has no attribute 'pagginate'
